/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_redknot_miaovideocutter_jni_MiaoVideoCutterJNI */

#ifndef _Included_com_redknot_miaovideocutter_jni_MiaoVideoCutterJNI
#define _Included_com_redknot_miaovideocutter_jni_MiaoVideoCutterJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_redknot_miaovideocutter_jni_MiaoVideoCutterJNI
 * Method:    get_core_version
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_redknot_miaovideocutter_jni_MiaoVideoCutterJNI_get_1core_1version
        (JNIEnv *, jclass);

/*
 * Class:     com_redknot_miaovideocutter_jni_MiaoVideoCutterJNI
 * Method:    video_format_session_demo
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_redknot_miaovideocutter_jni_MiaoVideoCutterJNI_video_1format_1session_1demo
        (JNIEnv *, jclass, jstring);

/*
 * Class:     com_redknot_miaovideocutter_jni_MiaoVideoCutterJNI
 * Method:    video_format_session_init
 * Signature: (Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_com_redknot_miaovideocutter_jni_MiaoVideoCutterJNI_video_1format_1session_1init
        (JNIEnv *, jclass, jstring);

/*
 * Class:     com_redknot_miaovideocutter_jni_MiaoVideoCutterJNI
 * Method:    video_format_session_uninit
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_redknot_miaovideocutter_jni_MiaoVideoCutterJNI_video_1format_1session_1uninit
        (JNIEnv *, jclass, jlong);

/*
 * Class:     com_redknot_miaovideocutter_jni_MiaoVideoCutterJNI
 * Method:    video_format_session_GetStreamCount
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_redknot_miaovideocutter_jni_MiaoVideoCutterJNI_video_1format_1session_1GetStreamCount
        (JNIEnv *, jclass, jlong);

/*
 * Class:     com_redknot_miaovideocutter_jni_MiaoVideoCutterJNI
 * Method:    video_format_session_GetStreamType
 * Signature: (JI)I
 */
JNIEXPORT jint JNICALL Java_com_redknot_miaovideocutter_jni_MiaoVideoCutterJNI_video_1format_1session_1GetStreamType
        (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     com_redknot_miaovideocutter_jni_MiaoVideoCutterJNI
 * Method:    video_format_session_GetStreamDuration
 * Signature: (JI)D
 */
JNIEXPORT jdouble JNICALL Java_com_redknot_miaovideocutter_jni_MiaoVideoCutterJNI_video_1format_1session_1GetStreamDuration
        (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     com_redknot_miaovideocutter_jni_MiaoVideoCutterJNI
 * Method:    video_format_session_GetStreamWidth
 * Signature: (JI)I
 */
JNIEXPORT jint JNICALL Java_com_redknot_miaovideocutter_jni_MiaoVideoCutterJNI_video_1format_1session_1GetStreamWidth
        (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     com_redknot_miaovideocutter_jni_MiaoVideoCutterJNI
 * Method:    video_format_session_GetStreamHeight
 * Signature: (JI)I
 */
JNIEXPORT jint JNICALL Java_com_redknot_miaovideocutter_jni_MiaoVideoCutterJNI_video_1format_1session_1GetStreamHeight
        (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     com_redknot_miaovideocutter_jni_MiaoVideoCutterJNI
 * Method:    video_format_session_GetFrameCount
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_redknot_miaovideocutter_jni_MiaoVideoCutterJNI_video_1format_1session_1GetFrameCount
        (JNIEnv *, jclass, jlong);

/*
 * Class:     com_redknot_miaovideocutter_jni_MiaoVideoCutterJNI
 * Method:    video_format_session_GetFrameYUV
 * Signature: (JID)J
 */
JNIEXPORT jlong JNICALL Java_com_redknot_miaovideocutter_jni_MiaoVideoCutterJNI_video_1format_1session_1GetFrameYUV
        (JNIEnv *, jclass, jlong, jint, jdouble);

/*
 * Class:     com_redknot_miaovideocutter_jni_MiaoVideoCutterJNI
 * Method:    video_format_session_GetRGBA8888
 * Signature: (J)[I
 */
JNIEXPORT jintArray JNICALL Java_com_redknot_miaovideocutter_jni_MiaoVideoCutterJNI_video_1format_1session_1GetRGBA8888
        (JNIEnv *, jclass, jlong);

/*
 * Class:     com_redknot_miaovideocutter_jni_MiaoVideoCutterJNI
 * Method:    video_format_session_YuvUninit
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_redknot_miaovideocutter_jni_MiaoVideoCutterJNI_video_1format_1session_1YuvUninit
        (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
