/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_redknot_miaovideocutter_jni_MiaoVideoCutterJNI */

#ifndef _Included_com_redknot_miaovideocutter_jni_MiaoVideoCutterJNI
#define _Included_com_redknot_miaovideocutter_jni_MiaoVideoCutterJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_redknot_miaovideocutter_jni_MiaoVideoCutterJNI
 * Method:    get_core_version
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_redknot_miaovideocutter_jni_MiaoVideoCutterJNI_get_1core_1version
  (JNIEnv *, jclass);

/*
 * Class:     com_redknot_miaovideocutter_jni_MiaoVideoCutterJNI
 * Method:    video_format_session_init
 * Signature: (Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_com_redknot_miaovideocutter_jni_MiaoVideoCutterJNI_video_1format_1session_1init
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_redknot_miaovideocutter_jni_MiaoVideoCutterJNI
 * Method:    video_format_session_uninit
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_redknot_miaovideocutter_jni_MiaoVideoCutterJNI_video_1format_1session_1uninit
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_redknot_miaovideocutter_jni_MiaoVideoCutterJNI
 * Method:    video_format_session_GetStreamCount
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_redknot_miaovideocutter_jni_MiaoVideoCutterJNI_video_1format_1session_1GetStreamCount
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_redknot_miaovideocutter_jni_MiaoVideoCutterJNI
 * Method:    video_format_session_GetStreamType
 * Signature: (JI)I
 */
JNIEXPORT jint JNICALL Java_com_redknot_miaovideocutter_jni_MiaoVideoCutterJNI_video_1format_1session_1GetStreamType
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     com_redknot_miaovideocutter_jni_MiaoVideoCutterJNI
 * Method:    video_format_session_GetStreamDuration
 * Signature: (JI)D
 */
JNIEXPORT jdouble JNICALL Java_com_redknot_miaovideocutter_jni_MiaoVideoCutterJNI_video_1format_1session_1GetStreamDuration
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     com_redknot_miaovideocutter_jni_MiaoVideoCutterJNI
 * Method:    video_format_session_GetFrameCount
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_redknot_miaovideocutter_jni_MiaoVideoCutterJNI_video_1format_1session_1GetFrameCount
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_redknot_miaovideocutter_jni_MiaoVideoCutterJNI
 * Method:    video_format_session_GetFrameYUV
 * Signature: (JID)J
 */
JNIEXPORT jlong JNICALL Java_com_redknot_miaovideocutter_jni_MiaoVideoCutterJNI_video_1format_1session_1GetFrameYUV
  (JNIEnv *, jclass, jlong, jint, jdouble);

#ifdef __cplusplus
}
#endif
#endif
