/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_redknot_miaovideocutter_jni_MiaoVideoCutterJNI */

#ifndef _Included_com_redknot_miaovideocutter_jni_MiaoVideoCutterJNI
#define _Included_com_redknot_miaovideocutter_jni_MiaoVideoCutterJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_redknot_miaovideocutter_jni_MiaoVideoCutterJNI
 * Method:    get_core_version
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_redknot_miaovideocutter_jni_MiaoVideoCutterJNI_get_1core_1version
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
